### ISSUE TITLE
Server freezes and crashes when player joins

### ISSUE THREAD

**Issue by SilverSlayer547** [Harve/GoCreateModpack#5]
The server runs perfectly fine until someone joins the server, then it completely freezes and eventually crashes.

[crash-2021-07-13_15.51.48-server.txt](https://github.com/Harve/GoCreateModpack/files/6811936/crash-2021-07-13_15.51.48-server.txt)

**Comment by Harve** [comment]
Hello,
In server.properties file try changing max tick time to 999999  or -1 as the server watchdog is crashing the server on purpose.

**Comment by Fzoss** [comment]
![image](https://user-images.githubusercontent.com/20693292/125718837-c858833b-c9c6-4253-887d-74d011f1392d.png)

I also have some crashes here caused by Watchdog, but there are more other errors, such as a lot of NullPointerExceptions, but my friends have lost patience and want me to replace a modpacks

**Comment by Harve** [comment]
I believe I've found the source of a few of the crashes, however I cannot find out what is going on unless you provide the crash logs

**Comment by Harve** [comment]
Please let me know by opening a new issue if this still occurs in 1.3.0
